# Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]
 
# Switches
set_property PACKAGE_PIN V17 [get_ports {instr[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {instr[0]}]
set_property PACKAGE_PIN V16 [get_ports {instr[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {instr[1]}]
set_property PACKAGE_PIN W16 [get_ports {instr[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {instr[2]}]
set_property PACKAGE_PIN W17 [get_ports {instr[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {instr[3]}]
set_property PACKAGE_PIN W15 [get_ports {instr[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {instr[4]}]
set_property PACKAGE_PIN V15 [get_ports {instr[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {instr[5]}]
set_property PACKAGE_PIN W14 [get_ports {instr[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {instr[6]}]
set_property PACKAGE_PIN W13 [get_ports {instr[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {instr[7]}]
	
set_property PACKAGE_PIN V2 [get_ports {instr[8]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {instr[8]}]
set_property PACKAGE_PIN T3 [get_ports {instr[9]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {instr[9]}]
set_property PACKAGE_PIN T2 [get_ports {instr[10]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {instr[10]}]
set_property PACKAGE_PIN R3 [get_ports {instr[11]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {instr[11]}]

## LEDs
set_property PACKAGE_PIN U16 [get_ports {displayed_number[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {displayed_number[0]}]
set_property PACKAGE_PIN E19 [get_ports {displayed_number[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {displayed_number[1]}]
set_property PACKAGE_PIN U19 [get_ports {displayed_number[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {displayed_number[2]}]
set_property PACKAGE_PIN V19 [get_ports {displayed_number[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {displayed_number[3]}]
set_property PACKAGE_PIN W18 [get_ports {displayed_number[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {displayed_number[4]}]
set_property PACKAGE_PIN U15 [get_ports {displayed_number[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {displayed_number[5]}]
set_property PACKAGE_PIN U14 [get_ports {displayed_number[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {displayed_number[6]}]
set_property PACKAGE_PIN V14 [get_ports {displayed_number[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {displayed_number[7]}]
set_property PACKAGE_PIN V13 [get_ports {displayed_number[8]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {displayed_number[8]}]
set_property PACKAGE_PIN V3 [get_ports {displayed_number[9]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {displayed_number[9]}]
set_property PACKAGE_PIN W3 [get_ports {displayed_number[10]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {displayed_number[10]}]
set_property PACKAGE_PIN U3 [get_ports {displayed_number[11]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {displayed_number[11]}]
set_property PACKAGE_PIN P3 [get_ports {displayed_number[12]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {displayed_number[12]}]
set_property PACKAGE_PIN N3 [get_ports {displayed_number[13]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {displayed_number[13]}]
set_property PACKAGE_PIN P1 [get_ports {displayed_number[14]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {displayed_number[14]}]
set_property PACKAGE_PIN L1 [get_ports {displayed_number[15]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {displayed_number[15]}]
	
#7 segment display
set_property PACKAGE_PIN W7 [get_ports {LED_out[6]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[6]}]
set_property PACKAGE_PIN W6 [get_ports {LED_out[5]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[5]}]
set_property PACKAGE_PIN U8 [get_ports {LED_out[4]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[4]}]
set_property PACKAGE_PIN V8 [get_ports {LED_out[3]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[3]}]
set_property PACKAGE_PIN U5 [get_ports {LED_out[2]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[2]}]
set_property PACKAGE_PIN V5 [get_ports {LED_out[1]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[1]}]
set_property PACKAGE_PIN U7 [get_ports {LED_out[0]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[0]}]
set_property PACKAGE_PIN U2 [get_ports {Anode_Activate[0]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {Anode_Activate[0]}]
set_property PACKAGE_PIN U4 [get_ports {Anode_Activate[1]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {Anode_Activate[1]}]
set_property PACKAGE_PIN V4 [get_ports {Anode_Activate[2]}]               
   set_property IOSTANDARD LVCMOS33 [get_ports {Anode_Activate[2]}]
set_property PACKAGE_PIN W4 [get_ports {Anode_Activate[3]}]          
   set_property IOSTANDARD LVCMOS33 [get_ports {Anode_Activate[3]}]

##Buttons
set_property PACKAGE_PIN U18 [get_ports instruction]						
	set_property IOSTANDARD LVCMOS33 [get_ports instruction]

